version: '3.7'

services:
  app:
    image: nikolaik/python-nodejs
    container_name: panitech-front-end
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm run start"
    ports:
      - "3020:3020"